# Generated by Django 3.2.9 on 2021-11-27 01:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_rename_user_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='booked_trips',
        ),
        migrations.RemoveField(
            model_name='users',
            name='reviews',
        ),
        migrations.RemoveField(
            model_name='users',
            name='saved_trips',
        ),
        migrations.CreateModel(
            name='BookedTrips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_name', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pages.users')),
            ],
        ),
    ]
