# Generated by Django 3.2.9 on 2021-11-16 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_remove_user_time_stamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='question3',
            new_name='answer1',
        ),
        migrations.AddField(
            model_name='user',
            name='answer2',
            field=models.CharField(default='', max_length=200),
        ),
    ]
