# Generated by Django 3.2.9 on 2021-11-14 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20211114_0004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='time_stamp',
        ),
    ]
