# Generated by Django 3.2.9 on 2021-11-27 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_auto_20211126_2040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookedtrips',
            name='user',
        ),
        migrations.AlterField(
            model_name='bookedtrips',
            name='user_message',
            field=models.TextField(blank=True),
        ),
    ]
