# Generated by Django 3.2.9 on 2021-11-27 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_auto_20211126_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookedtrips',
            name='user_id',
            field=models.CharField(default='0', max_length=200),
        ),
    ]
